### ISSUE TITLE
[May 26] no data from any of the stations

### ISSUE THREAD

**Issue by nschloe** [opendata-stuttgart/sensors-software#214]
As of now, no sensor sends data upstream; pick any in https://maps.luftdaten.info/#10/48.2909/8.9730.

![sc](https://user-images.githubusercontent.com/181628/40575673-77d9f4f8-60e9-11e8-91a3-8df94e83224c.png)

From what I can tell in my own station, the sensor itself if working fine.

**Comment by ricki-z** [comment]
Not sending data upstream can't be true. There are values (5 and 5 for ID 5894) shown in the table.
The server was restarted for a security update (Meltdown + Spectre patches). But the grafana instance didn't came up after this. Now the graphs should be shown again.

**Comment by nschloe** [comment]
Indeed they are. Thanks for the quick fix! Btw, I'm assuming the jagged data in

![k](https://user-images.githubusercontent.com/181628/40576829-f7e25c68-60fc-11e8-85d4-f902718fecf8.png)

is also due to some server problems? (It's jagged for all sensors in the map at the same times.)

**Comment by ricki-z** [comment]
This should also be fixed now.

**Comment by nschloe** [comment]
@ricki-z Jagged data still occurs now; e.g., Sunday evening https://api.luftdaten.info/grafana/render/dashboard-solo/db/single-sensor-view?orgId=1&panelId=2&width=800&height=500&tz=UTC%2B02%3A00&var-node=12338.
